geospaas/base_viewer/urls.py
from django.urls import path

from geospaas.base_viewer.views import IndexView, get_geometry_geojson


app_name = 'base_viewer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('geometry/<int:pk>', get_geometry_geojson, name='geometry_geojson'),
]

geospaas/base_viewer/forms.py
from django.contrib.gis import forms
from django.utils import timezone
from leaflet.forms.widgets import LeafletWidget

from geospaas.catalog.models import Source


class BaseSearchForm(forms.Form):
    """ Basic version of form for basic seaching of django-geospaas metadata """
    polygon = forms.GeometryField(label=False,
                                  widget=LeafletWidget(attrs={
                                      'settings_overrides': {
                                          'DEFAULT_CENTER': (89.0, 179.0),
                                          'DEFAULT_ZOOM': 1,
                                          'NO_GLOBALS': False,
                                          'PLUGINS': {'forms': {'auto-include': True}},
                                      }
                                  }),
                                  required=False)
    time_coverage_start = forms.DateTimeField(
        initial=timezone.datetime(2000, 1, 1, tzinfo=timezone.utc))
    time_coverage_end = forms.DateTimeField(initial=timezone.now())
    source = forms.ModelMultipleChoiceField(
        Source.objects.all(), required=False)

    def filter(self, ds):
        """ Filtering method of the form. All filtering processes are coded here """
        # filtering based on time
        t_0 = self.cleaned_data['time_coverage_start']
        t_1 = self.cleaned_data['time_coverage_end']
        # Too early datasets are excluded from the filtering results
        ds = ds.exclude(time_coverage_end__lte=t_0)

        # Too late datasets are excluded from the filtering results
        ds = ds.exclude(time_coverage_start__gt=t_1)

        src = self.cleaned_data.get('source', None)
        # Just the one(s) with correct selected source should pass the filtering actions
        # if Source is given in the input form
        if src:
            ds = ds.filter(source__in=src)

        # spatial filtering
        if self.cleaned_data['polygon']:
            # filtering by user provided polygon
            ds = ds.filter(
                geographic_location__geometry__intersects=self.cleaned_data['polygon'])

        # sorting
        ds = ds.order_by('time_coverage_start')
        return ds

geospaas/base_viewer/views.py
from django.core.paginator import Paginator
from django.core.serializers import serialize
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View
from django.conf import settings

from geospaas.base_viewer.forms import BaseSearchForm
from geospaas.catalog.models import Dataset, GeographicLocation
from geospaas.catalog.managers import LOCAL_FILE_SERVICE

def get_geometry_geojson(request, pk, *args, **kwargs):
    """ Get GeographicLocation.Geometry as GeoJSON

    Parameters
    ----------
    pk : int
        primary key of GeographicLocation object

    Returns
    -------
    response : HttpResponse
        GeoJSON with geometry of GeographicLocation

    """
    gl = GeographicLocation.objects.filter(pk=pk)
    if gl.count() == 0:
        geojson = '{}'
    else:
        geojson = serialize('geojson', gl)
    return HttpResponse(geojson)


class IndexView(View):
    """ The class-based view for processing both GET and POST methods of basic version of viewer """
    form_class = BaseSearchForm
    main_template = 'base_viewer/ds_info.html'
    viewname = 'index'
    paginate_by = 20

    @classmethod
    def get_all_datasets(cls):
        """ Retrieve all dataset(s) from the database"""
        return Dataset.objects.order_by('time_coverage_start').exclude(geographic_location__isnull=True)

    @classmethod
    def get_filtered_datasets(cls, form):
        """ Retrieve filtered list of dataset(s) based on form inputs """
        ds = cls.get_all_datasets()
        return form.filter(ds)

    @classmethod
    def paginate(cls, ds, request):
        """ Paginate datasets and return paginator at current page"""
        paginator = Paginator(ds, cls.paginate_by)
        page_number = request.POST.get('page', 1)
        page_obj = paginator.get_page(page_number)
        return page_obj

    @classmethod
    def set_context(cls, form, page_obj):
        """ Prepare all context for rendering """
        context = {}
        context['form'] = form
        context['page_obj'] = page_obj
        context['show_local_address'] = getattr(settings, 'SHOW_LOCAL_ADDRESS', False)
        context['local_file_service'] = LOCAL_FILE_SERVICE
        return context

    def get(self, request, *args, **kwargs):
        """ Render page if no data is given """
        form = self.form_class()
        form.is_valid()
        ds = self.get_all_datasets()
        page_obj = self.paginate(ds, request)
        context = self.set_context(form, page_obj)
        return render(request, self.main_template, context)

    def post(self, request, *args, **kwargs):
        """ Render page when user submits search request """
        form = self.form_class(request.POST)
        form.is_valid()
        ds = self.get_filtered_datasets(form)
        page_obj = self.paginate(ds, request)
        context = self.set_context(form, page_obj)
        return render(request, self.main_template, context)

geospaas/base_viewer/templates/base_viewer/ds_info.html
{% extends "base_viewer/elements.html" %}
##############################################################################################################
{% block ds_info %}
    {% block ds_detailed_info %}
    {% endblock ds_detailed_info %}
    {% for url in ds.dataseturi_set.all %}
    <div class="attr_title">Address:</div>
    {% if show_local_address or url.service != local_file_service %}
    <div class="attr_content">{{ url.uri|escape|urlize}} </div>
    {% else %}
    <div class="attr_content">hidden local address of dataset</div>
    {% endif %}
    {% endfor %}
{% endblock ds_info %}

geospaas/base_viewer/templates/base_viewer/elements.html
{% extends "base_viewer/page_structure.html" %}
##############################################################################################################
{% block content_result %}
<table border=1 style="width:100%">
  <tr>
    {% block headers %}
    <th>Datasets</th>
    {% endblock headers %}
  </tr>

  {% if page_obj %}

  {% for ds in page_obj %}
  <tr class="dataset_row" ajax_url="{% url 'base_viewer:geometry_geojson' ds.geographic_location.pk %}">
    <td>
      {% block ds_info %}
      {% endblock ds_info %}
    </td>
    {% endfor %}
    {% else %}
  <tr>
    <td colspan=10 class="place_ds">No datasets found</td>
  </tr>
  {% endif %}
</table>

{% endblock content_result %}
##############################################################################################################
{% block pagination_button_result %}
<div class="pagination">
  <span class="step-links">
    <button form='search_form' {% if page_obj.has_previous %} name="page" value="{{ page_obj.previous_page_number }}"
      type="submit" {% else %} disabled="disabled" {% endif %}>
      Previous
    </button>

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    <button form='search_form' {% if page_obj.has_next %} name="page" value="{{ page_obj.next_page_number }}"
      type="submit" {% else %} disabled="disabled" {% endif %}>
      Next
    </button>
  </span>
</div>
{% endblock pagination_button_result %}
##############################################################################################################
{% block contentmap %}

<form method="post" id='search_form'>
  {% csrf_token %}
  <div id="para_FORM">
    <div id="map">{{form.polygon}}</div>
    <div class="attr_title_itself">Time coverage start (UTC):</div>
    <div class="form_content">{{form.time_coverage_start}}</div>
    <div class="attr_title_itself">Time coverage end (UTC):</div>
    <div class="form_content">{{form.time_coverage_end}}</div>
    <div class="attr_title_itself">Source:</div>
    <div class="form_content">{{form.source}}</div>
    <div class="attr_title_itself">Name (or part of the name) of parameter:</div>
    <div class="form_content">{{form.nameparameters}}</div>

  </div>
  <input type="submit" value="Search all meta-data" />
</form>
{% endblock contentmap %}

geospaas/base_viewer/templates/base_viewer/origin_of_templates.html
{% load static %}
{% load leaflet_tags %}
<html>

<head>
	<title>Meta-data finder</title>
	{% leaflet_js plugins="ALL" %}
	{% leaflet_css plugins="ALL" %}
<link rel="stylesheet" href="{% static 'base_viewer/styles.css' %}" >

</head>

<body class="body" >
	<div id="para_container">

		<div id=content class="para2"><!--start of contentmap-->
			{% block contentmap %}
			{% endblock contentmap%}
		</div><!--end of contentmap-->

		<div id=result class="para2"><!--start of result section-->
			{% block content_result %}
			{% endblock content_result%}
		</div><!--end of result section-->

		<div id="searchbox"><!--start of searchbox-->
			{% block searchbox %}
			{% endblock searchbox %}
		</div><!--end of searchbox-->
    </div>
</body>

</html>

geospaas/base_viewer/templates/base_viewer/page_structure.html
{% load static %}
{% load leaflet_tags %}
<html>

<head>
    <title>Meta-data finder</title>
    {% leaflet_js plugins="ALL" %}
    {% leaflet_css plugins="ALL" %}
    <link rel="stylesheet" href="{% static 'base_viewer/styles.css' %}" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src='{% static "base_viewer/js/leaflet.ajax.min.js" %}'></script>
    <script src='{% static "base_viewer/js/base_viewer.js" %}'></script>
</head>

<body class="body">
    <div id="para_container">

        <div id=content class="para2">
            <!--start of contentmap-->
            {% block contentmap %}
            {% endblock contentmap%}
        </div>
        <!--end of contentmap-->

        <div id=result class="para2">
            <!--start of result section-->
            {% block content_result %}
            {% endblock content_result%}
        </div>
        <!--end of result section-->
        <div id=pgbutton class="para2">
            <!--start of pagination button section-->
            {% block pagination_button_result %}
            {% endblock pagination_button_result%}
        </div>
        <!--end of button section-->

    </div>
</body>

</html>